### ISSUE TITLE
Multi-GPU

### ISSUE THREAD

**Issue by fengziyue** [nianticlabs/manydepth#2]
Hi:

Seems the training time is similar to Monodepth2, pretty efficient!
I'm wondering if it's possible to utilize multiple GPUs?

Thank you

**Comment by mdfirman** [comment]
Hi @fengziyue – thanks for your interest here!

We haven't explored multi-GPU at all and it isn't something we are planning to support. As you say – training times are pretty small already.

I would expect that a multi-GPU version wouldn't be too hard to implement though. (There are some discussions around this on the monodepth2 repo, e.g. [here](https://github.com/nianticlabs/monodepth2/issues/5))

Thanks,

Michael

**Comment by agenthong** [comment]
Hi! @mdfirman @JamieWatson683 - Thanks for helping us!

I've tried some changes through [here](https://github.com/nianticlabs/monodepth2/issues/5).

But there still are some differences. I set `self.is_cuda = True` in `resnet_encoder`  so that put `warp_depths` and `_invk` on same device. An error happens here:

```
Traceback (most recent call last):
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hzc/manydepth-cost/manydepth/train.py", line 16, in <module>
    trainer.train()
  File "/home/hzc/manydepth-cost/manydepth/trainer.py", line 249, in train
    self.run_epoch()
  File "/home/hzc/manydepth-cost/manydepth/trainer.py", line 265, in run_epoch
    outputs, losses = self.process_batch(inputs, is_train=True)
  File "/home/hzc/manydepth-cost/manydepth/trainer.py", line 364, in process_batch
    max_depth_bin=max_depth_bin)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in forward
    return self.gather(outputs, self.output_device)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 174, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 56, in forward
    'Gather function not implemented for CPU tensors'
AssertionError: Gather function not implemented for CPU tensors
```

So how can I solve this problem?
