### ISSUE TITLE
AssertionError: size of input tensor and input format are different.

### ISSUE THREAD

**Issue by agenthong** [nianticlabs/manydepth#20]
```
Traceback (most recent call last):
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hzc/manydepth/manydepth/train.py", line 16, in <module>
    trainer.train()
  File "/home/hzc/manydepth/manydepth/trainer.py", line 211, in train
    self.run_epoch()
  File "/home/hzc/manydepth/manydepth/trainer.py", line 242, in run_epoch
    self.log("train", inputs, outputs, losses)
  File "/home/hzc/manydepth/manydepth/trainer.py", line 742, in log
    consistency_target, self.step)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/tensorboardX/writer.py", line 608, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/tensorboardX/summary.py", line 283, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/tensorboardX/utils.py", line 103, in convert_to_HWC
    tensor shape: {}, input_format: {}".format(tensor.shape, input_format)
AssertionError: size of input tensor and input format are different.         tensor shape: (1, 3, 192, 640), input_format: CHW
```

I don't edit any codes. But an error occurs when I train. How can I solve this?
Thanks in advance.

**Comment by mdfirman** [comment]
Hi @agenthong , thanks for trying out our repo!

Could you please check the version of tensorboardX you are using?  Our repo is designed to work with version 1.5, as specified in `environment.yml`.

You can run:
```
pip freeze | grep tensorboardX
```
You should get the following output:
```
tensorboardX==1.5
```

**Comment by agenthong** [comment]
Thanks a lot!
My tensorboardX version doesn't match. 
I have fixed it.
