### ISSUE TITLE
How can I save predicted depth map?

### ISSUE THREAD

**Issue by agenthong** [nianticlabs/manydepth#23]
It's a great work! But I got one question.

After evaluating the model, how can I save the predicted depth map?
I notice that there is an option '**eval_split**' in the code and I think it can save predicted depth map. 
If I set '**eval_split**' is '**benchmark**', an error occured:
`
Traceback (most recent call last):
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hzc/manydepth/manydepth/evaluate_depth.py", line 371, in <module>
    evaluate(options.parse())
  File "/home/hzc/manydepth/manydepth/evaluate_depth.py", line 158, in evaluate
    for i, data in tqdm.tqdm(enumerate(dataloader)):
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hzc/anaconda3/envs/cas/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hzc/manydepth/manydepth/datasets/mono_dataset.py", line 157, in __getitem__
    folder, frame_index + i, side, do_flip)
  File "/home/hzc/manydepth/manydepth/datasets/kitti_dataset.py", line 65, in get_color
    color = self.loader(self.get_image_path(folder, frame_index, side))
  File "/home/hzc/manydepth/manydepth/datasets/kitti_dataset.py", line 82, in get_image_path
    self.data_path, folder, "image_0{}/data".format(self.side_map[side]), f_str)
KeyError: None

`

**Comment by JamieWatson683** [comment]
Hi, thanks for your interest in the repo!

Sure - to save the predicted disparities after evaluation you can add the `--save_pred_disps` option to the command line, this should save out a block of predictions.

As for running on the benchmark data - I see the same error as you, and I actually see the same when trying to run using the Monodepth2 repo (on which Manydepth is based), so I will bring this up with the authors and see if we can get a push fixed.

Thanks a lot for finding this bug!

**Comment by agenthong** [comment]
> Hi, thanks for your interest in the repo!
> 
> Sure - to save the predicted disparities after evaluation you can add the `--save_pred_disps` option to the command line, this should save out a block of predictions.
> 
> As for running on the benchmark data - I see the same error as you, and I actually see the same when trying to run using the Monodepth2 repo (on which Manydepth is based), so I will bring this up with the authors and see if we can get a push fixed.
> 
> Thanks a lot for finding this bug!

Thanks for replying!
I've saved disparity map by this way. Is there any demo to convert disparity map to depth map in this repo?

**Comment by JamieWatson683** [comment]
The script will save out inverse depth (which with a slight abuse of terminology refer to as "disparity" - to so convert to depth you can just do `depth = 1 / disparity`. 

However, since we have trained from monocular sequences only, our predictions will be in an arbitrary scale. To convert to real world scale you can apply the same median scaling that happens when we are evaluating the model on line 336 https://github.com/nianticlabs/manydepth/blob/28fbbcfa4370eb9c28860b8ab72b09547c0d14d0/manydepth/evaluate_depth.py#L336 and save out the `pred_depth` after line 339. 

Let me know if that works for you.
